### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by kasei** [linked-art/crom#11]
Running tests on a fresh checkout, I get two errors related to the recent updates in extract.py:

1. The use of the `@contextmanager` decorator introduced in a recent commit:

https://github.com/linked-art/crom/blob/d55e207eb1395eada52878d3f1a3bd763ff20e54/cromulent/extract.py#L728

Does this need an associated `from contextlib import contextmanager`?

2. The use of f-strings seem to prevent use on python 2.7. That's fine, but setup.py (and some comments throughout the rep) still seems to indicate support for 2.7.

https://github.com/linked-art/crom/blob/d55e207eb1395eada52878d3f1a3bd763ff20e54/cromulent/extract.py#L725

**Comment by azaroth42** [comment]
Oops, f-strings and 2.7...

**Comment by azaroth42** [comment]
Closing ... think we can let 2.x die.
