### ISSUE TITLE
AttributeAssignment's assigned definition says array, example and crom use object

### ISSUE THREAD

**Issue by bluebinary** [linked-art/crom#33]
Thank you @azaroth42 for fixing [#445](https://github.com/linked-art/linked.art/issues/445) in the Linked.art context, it is a huge help!

I pulled down the latest version of CROM and tried to generate the output again, however I found that CROM is still only emitting the last value set on the `AttributeAssignment` entity’s `assigned` property, rather than all of the values that have been set, as is the case with other properties that have multiplicity enabled.

After some additional research reviewing CROM and determining the code path followed when a value is set on the `assigned` property, I traced the issue to the current implementation of the `add_attribute_assignment_check()` method (and it’s sub-method, `aa_set_assigned()`) within `crom/cromulent/vocab.py` which sets a [custom setter method](https://github.com/linked-art/crom/blob/be88023b657324349640430b43b496eafe5d2867/cromulent/vocab.py#L763) on an `AttributeAssignment` entity’s `assigned` property.

When almost any value is assigned to a model entity in CROM, the `_setattr_()` and `_set_magic_resource()` methods in `crom/cromulent/model.py` are [invoked](https://github.com/linked-art/crom/blob/be88023b657324349640430b43b496eafe5d2867/cromulent/model.py#L751) (as most properties we are trying to set for the purposes of data modeling using CROM are virtual properties defined in the model, rather than preexisting class or instance properties), and as this `aa_set_assigned()` custom setter method has been configured for the `assigned` property, it is executed rather than the default code within the `_setattr_()` and `_set_magic_resource()` methods.

As `aa_set_assigned()` currently treats all assignments to the `assigned` property as though multiplicity is disabled for the property, it seems we need to modify the definition of this custom setter method in addition to the changes that have already made to the context and `crm_vocab.tsv` to fully enable support for multiplicity on the `assigned` property.

Do you have any suggestions as to how we could adjust the definition of `aa_set_assigned()` to support multiplicity now that it has been enabled in the model configuration (`crm_vocab.tsv`) and Linked.art context?

Would the following replacement definition of `aa_set_assigned()` work instead?

```
	def aa_set_assigned(self, value):
		assto_res = getattr(self, assto, None)
		if assto_res:
			p177_res = getattr(self, p177, None)
			assto_res._check_prop(p177_res, value)

		current = getattr(self, ass, None)
		if type(current) is not list:
			current = []
		
		if value is not None:
			current.append(value)
			value = current
		
		object.__setattr__(self, ass, value)
```

In my testing, the above code change resulted in the desired JSON-LD output whereby the `assigned` property contains as many values as have been assigned.

The change in the method definition is to first obtain the value of the `assigned` property (if any) into the variable named `current`, and if the current value is not a `list` type to make it one. The next step is to append the incoming `value` to the list (if `value` is not a `None` value), then the list held in `current` overwrites `value` which is then assigned to the instance’s `assigned` property via the usual call to `object.__setattr__()`.

I am not sure if any of the other method definitions in `crom/cromulent/vocab.py` also need adjusting in light of the multiplicity changes? In particular, perhaps the definition for `aa_set_assigned_property_type` may need adjusting given the recent changes to the naming convention for that property from `assigned_property_type` to `assigned_property_of_type` which I noticed also happened as part of the same `6037515d` commit that fixed the multiplicity of the `assigned` property?

Thank you for any insights or advice you can offer. I would be happy to submit a PR for the above change to the custom setter for the `assigned` property if you think the proposed change would add the necessary support for multiplicity on the property without causing any unintended side effects.

**Comment by azaroth42** [comment]
Almost -- it needs to also check in the other magic setter functions as well. Try latest (0.16.11) and see if it works?
